Repository vmware/python-script-for-esxi-imaging, pull requests merged in 2024-06, with the labels that each got.

#1 chore: add pull request template
  .github/pull_request_template.md
Labels: cla-not-required

#2 chore: add CODEOWNERS
  CODEOWNERS
Labels: cla-not-required, chore

#3 chore: Add code of conduct
  CODE_OF_CONDUCT.md
Labels: cla-not-required, chore

#4 chore(gh): add issue templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
Labels: cla-not-required, chore

#5 docs: update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla-not-required, chore

#6 docs: update `CODE_OF_CONDUCT.md`
  CODE_OF_CONDUCT.md
Labels: cla-not-required, chore

#7 chore: add python scripts and supporting files
  CHANGELOG.md
  LogUtility.py
  README.md
  constants.py
  create-custom-iso.py
  display-ks-content.py
  firstboot-scripts.txt
  re-image-hosts.json
Labels: cla-not-required, chore

#8 chore: update `LICENSE`
  LICENSE
Labels: chore, cla-not-required

#9 chore: add `NOTICE`
  NOTICE
Labels: chore, cla-not-required

#11 chore: add actions
  .github/labeler-issues.yml
  .github/labeler-pull-requests.yml
  .github/workflows/issues.yml
  .github/workflows/lock-threads.yml
  .github/workflows/pull-requests.yml
  .github/workflows/stale.yml
Labels: github-actions, chore, cla-not-required

#12 chore(ci): add release workflow
  .github/workflows/release.yml
Labels: ci, github-actions, needs-review, chore, cla-not-required

#13 chore: update `README.md`
  README.md
Labels: needs-review, chore, cla-not-required, documentation
